print('Welcome to the tip calculator 😁')
bill = input('What was the total bill? $ ')
percentage = input('What percentage tip would you like to give? 10,12 or 15? ')
people = input('How many people would you split the bill? ')
total = float(bill) / float(people) * (float(percentage) / 100 + 1)
print(f'Each person should pay $ {round(total, 2)}')
